In [93]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import json
import csv
import re

from flatten_json import flatten
from pandas.io.json import json_normalize


# Until fuction: line seperator
def print_dashes_and_ln():
    print('-'*100, '\n')
    
# Formatter to display all float format in 2 decimal format
#pd.options.display.float_format = '{:.2f}'.format

import warnings
warnings.filterwarnings('ignore')

In [119]:
f = open('stats_match.json')
data = json.load(f)
f.close()
data_flattened = [flatten(d) for d in data]
print(data_flattened)
team_df = pd.DataFrame(data_flattened)
#team_df.replace([], None)
#columns = [column for column in df.columns]
team_df = team_df[team_df.astype(str) != '[]']



#print(type(data))
#df = pd.Series(flatten_json(data,"__")).to_frame()
#df
#data = map( lambda x: flatten_json( x, "__" ), data )
#print(list(data.get('stat_team')))
#team_df = pd.DataFrame(data)

#Remove Columns with only One Value
team_df = team_df.loc[:,team_df.apply(pd.Series.nunique) > 1]
team_df
# Drop unwanted columns
#columns_to_drop =['bio__facebook','bio__instagram','bio__official_website']
#team_df.drop(columns_to_drop, inplace=True, axis = 1)

# Only drop columns which have at least 50% non-NaNs
#team_df.dropna(thresh=int(team_df.shape[0] * .5), inplace=True, axis=1)

#team_df.rename(columns=lambda x: x.replace('over_all_stats__', 'team_'), inplace=True)
#team_df.rename(columns=lambda x: x.replace('bio__', 'team_'), inplace=True)

#column for column in df.columns column.contains('over_all_stats__')
#print(df['team_max_win_margin__match_id'])
#print(df['team_highest_score__match_id'])
#df
#team_df.head()

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

,events_event_0_clock,events_event_0_defender_id,events_event_0_defenders_0,events_event_0_defenders_1,events_event_0_defending_capture_points,events_event_0_defending_points,events_event_0_defending_team_id,events_event_0_event,events_event_0_event_id,events_event_0_event_text,...,teams_team_1_stats_points_total,teams_team_1_stats_raids_Empty,teams_team_1_stats_raids_successful,teams_team_1_stats_raids_super_raids,teams_team_1_stats_raids_total,teams_team_1_stats_raids_unsuccessful,teams_team_1_stats_tackles_successful,teams_team_1_stats_tackles_super_tackles,teams_team_1_stats_tackles_total,teams_team_1_stats_tackles_unsuccessful
0,20:00,NaN,157.0,311.0,0,0,2,Successful Raid,1,Suraj Desai raids successfully,...,34,12,23,0,39,4,6,1,24,18
1,20:00,NaN,NaN,NaN,0,0,29,Empty Raid,3,Chandran Ranjit empty raid,...,29,17,11,0,37,9,10,2,21,11
2,19:58,NaN,42.0,NaN,0,0,28,Successful Raid,1,Chandran Ranjit raids successfully,...,21,14,12,0,36,10,4,0,23,19
3,20:00,NaN,NaN,NaN,0,0,2,Successful Raid,1,Sachin raids successfully,...,26,18,11,0,39,10,8,1,19,11
4,19:58,NaN,481.0,NaN,0,0,2,Successful Raid,1,Deepak Hooda raids successfully,...,24,15,13,1,38,10,3,0,21,18
5,19:59,NaN,161.0,763.0,0,0,7,Successful Raid,1,Chandran Ranjit raids successfully,...,32,17,19,0,42,6,9,0,23,14
6,20:00,NaN,123.0,NaN,0,0,2,Successful Raid,1,Maninder Singh raids successfully,...,30,15,16,0,38,7,6,1,20,14
7,20:00,NaN,NaN,NaN,0,0,2,Successful Raid,1,Pawan Sehrawat raids successfully,...,31,16,16,0,42,10,10,0,19,9
8,20:00,NaN,NaN,NaN,0,0,30,Empty Raid,3,Chandran Ranjit empty raid,...,27,18,13,1,42,11,8,1,23,15
9,19:59,2486.0,2486.0,NaN,1,1,5,Unsuccessful Raid,2,Chandran Ranjit unsuccessful raid,...,24,16,10,0,42,16,8,2,24,16
10,19:59,NaN,571.0,NaN,0,0,6,Successful Raid,1,Chandran Ranjit raids successfully,...,35,13,17,1,41,11,7,0,21,14
11,20:00,311.0,311.0,NaN,1,1,2,Unsuccessful Raid,2,Deepak Hooda unsuccessful raid,...,46,11,20,2,43,12,9,1,24,15
12,20:00,42.0,42.0,NaN,1,1,28,Unsuccessful Raid,2,Chandran Ranjit unsuccessful raid,...,47,19,17,2,41,5,13,1,23,10
13,20:00,NaN,NaN,NaN,0,0,2,Empty Raid,3,Ajay Thakur empty raid,...,34,9,20,0,41,12,3,0,28,25
14,20:00,NaN,NaN,NaN,0,0,2,Empty Raid,3,Sachin empty raid,...,30,15,16,0,42,11,5,1,21,16
15,20:00,NaN,311.0,NaN,0,0,2,Successful Raid,1,Siddharth Desai raids successfully,...,37,13,18,0,39,8,11,0,24,13
16,20:00,318.0,318.0,NaN,1,1,1,Unsuccessful Raid,2,Chandran Ranjit unsuccessful raid,...,39,13,16,0,42,13,10,0,26,16
17,19:59,NaN,NaN,NaN,0,0,30,Empty Raid,3,Maninder Singh empty raid,...,48,17,17,1,40,6,14,0,20,6
18,19:59,NaN,NaN,NaN,0,0,3,Empty Raid,3,Maninder Singh empty raid,...,25,21,11,0,42,10,8,3,20,12
19,19:59,NaN,NaN,NaN,0,0,4,Empty Raid,3,Pawan Kadian empty raid,...,23,17,10,0,39,12,7,2,27,20
20,20:00,NaN,318.0,NaN,0,0,1,Successful Raid,1,Maninder Singh raids successfully,...,43,9,24,1,40,7,8,0,31,23
21,20:00,733.0,733.0,NaN,1,1,5,Unsuccessful Raid,2,Maninder Singh unsuccessful raid,...,30,20,10,0,40,10,10,0,22,12
22,20:00,NaN,796.0,NaN,0,0,4,Successful Raid,1,Siddharth Desai raids successfully,...,29,18,10,0,39,11,10,0,20,10
23,20:00,NaN,NaN,NaN,0,0,4,Empty Raid,3,Sachin empty raid,...,28,19,15,0,40,6,7,0,17,10
24,20:00,NaN,123.0,NaN,0,0,2,Successful Raid,1,Maninder Singh raids successfully,...,30,15,16,0,38,7,6,1,20,14
25,20:00,NaN,NaN,NaN,0,0,6,Empty Raid,3,Maninder Singh empty raid,...,26,15,16,0,42,11,5,1,20,15
26,20:00,NaN,NaN,NaN,0,0,4,Empty Raid,3,Vikas Kandola empty raid,...,36,16,18,1,40,6,7,1,28,21
27,19:59,NaN,NaN,NaN,0,0,4,Empty Raid,3,Ajay Thakur empty raid,...,26,19,14,1,43,10,6,0,26,20
28,20:00,NaN,NaN,NaN,0,0,4,Empty Raid,3,Rishank Devadiga empty raid,...,29,19,12,0,45,14,9,3,20,11
29,19:59,NaN,2672.0,NaN,0,0,31,Successful Raid,1,Maninder Singh raids successfully,...,25,20,14,1,42,8,8,0,21,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,19:59,NaN,2330.0,NaN,0,0,30,Successful Raid,1,Siddharth Desai raids successfully,...,20,27,6,0,43,10,11,2,18,7
181,20:00,NaN,358.0,NaN,0,0,8,Successful Raid,1,Rohit Kumar raids successfully,...,47,13,18,1,40,9,13,6,28,15
182,19:59,NaN,2672.0,NaN,0,0,31,Successful Raid,1,Siddharth Desai raids successfully,...,30,18,12,0,39,9,16,0,24,8
183,20:00,NaN,796.0,NaN,0,0,4,Successful Raid,1,Siddharth Desai raids successfully,...,29,18,10,0,39,11,10,0,20,10
184,20:00,NaN,191.0,NaN,0,0,8,Successful Raid,1,Vikas Kandola raids successfully,...,40,16,21,0,41,4,10,0,28,18
185,19:59,NaN,290.0,NaN,0,0,3,Successful Raid,1,Siddharth Desai raids successfully,...,24,22,9,0,40,9,12,3,15,3
186,20:00,NaN,NaN,NaN,0,0,7,Empty Raid,3,Siddharth Desai empty raid,...,34,21,13,1,44,10,14,0,20,6
187,20:00,NaN,NaN,NaN,0,0,29,Successful Raid,1,Siddharth Desai raids successfully,...,30,15,17,0,43,11,7,1,24,17
188,19:59,358.0,358.0,NaN,1,1,8,Unsuccessful Raid,2,Rohit Kumar unsuccessful raid,...,39,15,21,2,44,8,8,0,30,22
189,19:59,NaN,358.0,482.0,0,0,8,Successful Raid,1,Arjun Deshwal raids successfully,...,41,16,16,0,40,8,15,0,23,8
190,20:00,NaN,311.0,NaN,0,0,2,Successful Raid,1,Siddharth Desai raids successfully,...,37,13,18,0,39,8,11,0,24,13
191,20:00,579.0,579.0,NaN,1,1,6,Unsuccessful Raid,2,Siddharth Desai unsuccessful raid,...,42,15,17,2,41,9,7,0,26,19
192,20:00,NaN,NaN,NaN,0,0,8,Successful Raid,1,Rahul Chaudhari raids successfully,...,39,19,15,1,42,8,14,1,23,9
193,20:00,NaN,NaN,NaN,0,0,29,Empty Raid,3,Chandran Ranjit empty raid,...,29,17,11,0,37,9,10,2,21,11
194,19:58,NaN,NaN,NaN,0,0,6,Empty Raid,3,Rahul Chaudhari empty raid,...,24,21,7,0,39,11,9,4,18,9
195,19:58,NaN,NaN,NaN,0,0,28,Empty Raid,3,Rahul Chaudhari empty raid,...,35,16,17,0,42,9,10,0,21,11
196,20:00,69.0,69.0,NaN,1,1,29,Unsuccessful Raid,2,Monu Goyat unsuccessful raid,...,28,16,11,0,38,11,10,0,21,11
197,19:59,NaN,71.0,NaN,0,0,29,Successful Raid,1,Sachin raids successfully,...,34,25,9,1,43,9,12,1,23,11
198,20:00,NaN,NaN,NaN,0,0,29,Successful Raid,1,Pawan Sehrawat raids successfully,...,32,18,16,0,40,6,9,1,20,11
199,20:00,NaN,161.0,NaN,0,0,7,Successful Raid,1,Rahul Chaudhari raids successfully,...,31,19,15,0,45,11,11,1,25,14
200,20:00,NaN,NaN,NaN,0,0,29,Empty Raid,3,Deepak Hooda empty raid,...,28,21,14,0,42,7,8,3,23,15
201,20:00,71.0,71.0,NaN,1,1,29,Unsuccessful Raid,2,Abhishek Singh unsuccessful raid,...,29,20,11,0,39,8,10,1,22,12
202,19:59,NaN,NaN,NaN,0,0,4,Empty Raid,3,Ajay Thakur empty raid,...,26,19,14,1,43,10,6,0,26,20
203,20:00,NaN,NaN,NaN,0,0,1,Empty Raid,3,Ajay Thakur empty raid,...,27,22,12,0,42,8,10,2,28,18
204,20:00,NaN,NaN,NaN,0,0,29,Successful Raid,1,Siddharth Desai raids successfully,...,30,15,17,0,43,11,7,1,24,17
205,20:00,NaN,NaN,NaN,0,0,2,Empty Raid,3,Ajay Thakur empty raid,...,34,9,20,0,41,12,3,0,28,25
206,19:59,NaN,NaN,NaN,0,0,6,Empty Raid,3,Rahul Chaudhari empty raid,...,51,21,20,2,46,5,13,1,26,13
207,20:00,NaN,NaN,NaN,0,0,28,Empty Raid,3,Rahul Chaudhari empty raid,...,43,20,16,1,44,8,14,1,32,18
208,20:00,2506.0,2506.0,NaN,1,1,29,Unsuccessful Raid,2,Manjeet unsuccessful raid,...,36,9,21,0,42,12,6,1,23,17
209,19:59,NaN,NaN,NaN,0,0,29,Empty Raid,3,Rishank Devadiga empty raid,...,22,19,9,0,42,14,7,0,20,13

In [138]:
f = open('stats_player.json')
data = json.load(f)
f.close()
data = map( lambda x: flatten_json( x, "__" ), data )
player_df = pd.DataFrame(list(data))

#Remove Columns with only One Value
player_df = player_df.loc[:,player_df.apply(pd.Series.nunique) > 1]

# Drop unwanted columns
#columns_to_drop =['player_has_additional_details','player_height','player_is_captain']
#df.drop(columns_to_drop, inplace=True, axis = 1)

# Only drop columns which have at least 50% non-NaNs
player_df.dropna(thresh=int(player_df.shape[0] * .5), inplace=True, axis=1)

player_df.rename(columns=lambda x: x.replace('over_all_stats__', 'player_'), inplace=True)
player_df.rename(columns=lambda x: x.replace('bio__', 'player_'), inplace=True)


#null_counts = player_df.isnull().sum()
#null_counts
# Drop any rows which have any nans
#df.player_player_id.dropna(inplace=True)
player_df

,player_date_of_birth,player_full_name,player_has_additional_details,player_height,player_is_captain,player_jersey_no,player_nationality,player_player_id,player_player_short_name,player_position_id,...,player_tackle_bonus_points,player_tackle_success_rate,player_tackles,player_total_capture_points,player_total_defending_points,player_total_raid_points,player_total_tackle_points,player_unsuccesful_tackles,player_unsuccess_raids,player_yellow_cards
0,Oct 30 1992,Takamitsu Kono,False,5.6 ft,nan,15.00,Japan,9.00,Takamitsu Kono,1.00,...,,100.00,1.00,,1.00,1.00,1.00,0.00,0.00,0.00
1,Jul 11 1986,Dong Ju Hong,False,5.8 ft,nan,55.00,Korea,11.00,Dong Ju Hong,1.00,...,,0.00,4.00,,0.00,2.00,0.00,4.00,4.00,0.00
2,Nov 6 1992,Jang Kun Lee,True,6 ft,0.00,4.00,Korea,12.00,Jang Kun Lee,8.00,...,,23.46,98.00,,23.00,453.00,23.00,78.00,223.00,0.00
3,Jul 5 1985,Seong Ryeol Kim,False,5.7 ft,nan,9.00,Korea,13.00,Seong Ryeol Kim,1.00,...,,33.33,30.00,,11.00,3.00,11.00,20.00,6.00,0.00
4,Apr 1 1984,Tae Deok Eom,False,5.6 ft,nan,66.00,Korea,14.00,Tae Deok Eom,1.00,...,,18.60,43.00,,8.00,14.00,8.00,36.00,12.00,0.00
5,Jan 6 1984,Sanjay Shrestha,False,5 ft 6 in,0.00,3.00,Nepal,15.00,Sanjay Shrestha,1.00,...,,0.00,0.00,,0.00,0.00,0.00,0.00,0.00,0.00
6,NaN,NaN,NaN,NaN,nan,nan,NaN,nan,NaN,nan,...,,50.00,2.00,,1.00,5.00,1.00,1.00,1.00,0.00
7,May 1 1986,Ajay Thakur,True,6 ft 1 in,1.00,7.00,India,26.00,Ajay Thakur,8.00,...,,25.60,82.00,,21.00,790.00,21.00,61.00,379.00,1.00
8,Apr 4 1991,Amit Singh Chhillar,False,5.6 ft,nan,4.00,India,28.00,Amit Singh Chhillar,3.00,...,,38.31,154.00,,59.00,1.00,59.00,99.00,1.00,0.00
9,Nov 20 1983,Anup Kumar,True,5.9 ft,nan,3.00,India,29.00,Anup Kumar,8.00,...,,39.88,173.00,,69.00,527.00,69.00,112.00,200.00,2.00
10,Nov 11 1991,Bhupender Singh,False,5.9 ft,nan,10.00,India,34.00,Bhupender Singh,1.00,...,,27.27,44.00,,12.00,71.00,12.00,33.00,51.00,0.00
11,Jun 7 1991,Chandran Ranjit,False,5 ft 10 in,0.00,66.00,India,36.00,Chandran Ranjit,8.00,...,,24.39,41.00,,10.00,290.00,10.00,33.00,165.00,0.00
12,Jun 10 1994,Deepak Niwas Hooda,True,5 ft 11 in,1.00,5.00,India,41.00,Deepak Hooda,1.00,...,,37.39,230.00,,86.00,833.00,86.00,152.00,325.00,0.00
13,Apr 21 1975,Dharmaraj Cheralathan,True,5 ft 9 in,1.00,7.00,India,42.00,Dharmaraj Cheralathan,10.00,...,,54.07,466.00,,252.00,42.00,252.00,238.00,10.00,0.00
14,Feb 3 1994,Dharmendra Singh,False,5 ft 7 in,0.00,16.00,India,43.00,Dharmendra Singh,3.00,...,0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00
15,Jun 8 1993,Gangadhari Mallesh,False,5.8 ft,nan,8.00,India,44.00,Gangadhari Mallesh,8.00,...,,40.74,54.00,,22.00,19.00,22.00,36.00,15.00,0.00
16,Mar 14 1995,Gurvinder Singh,False,5 ft 9 in,0.00,2.00,India,46.00,Gurvinder Singh,8.00,...,,27.69,65.00,,18.00,82.00,18.00,48.00,57.00,0.00
17,May 7 1983,Jasmer Singh Gulia,False,5.6 ft,nan,7.00,India,51.00,Jasmer Gulia,1.00,...,,45.41,240.00,,109.00,7.00,109.00,138.00,6.00,0.00
18,Apr 4 1984,Jasvir Singh,True,5.5 ft,nan,2.00,India,52.00,Jasvir Singh,8.00,...,,36.78,87.00,,32.00,380.00,32.00,62.00,216.00,2.00
19,Apr 21 1995,Jeeva Gopal,NaN,NaN,nan,6.00,India,53.00,Jeeva Gopal,4.00,...,,17.24,58.00,,12.00,0.00,12.00,48.00,2.00,0.00
20,Jun 1 1981,Jeeva Kumar,True,5 ft 5 in,0.00,6.00,India,54.00,Jeeva Kumar,5.00,...,,46.47,482.00,,224.00,1.00,224.00,280.00,0.00,0.00
21,Dec 18 1992,Kashiling Adake,True,6.0 ft,nan,11.00,India,58.00,Kashiling Adake,8.00,...,,39.23,130.00,,51.00,561.00,51.00,86.00,264.00,0.00
22,NaN,NaN,NaN,NaN,nan,nan,NaN,nan,NaN,nan,...,,46.51,86.00,,40.00,0.00,40.00,49.00,0.00,0.00
23,Feb 22 1990,Mahesh Goud,True,6.0 ft,nan,2.00,India,66.00,Mahesh Goud,8.00,...,,31.57,76.00,,24.00,165.00,24.00,55.00,115.00,0.00
24,Apr 24 1992,Mahipal Narwal,NaN,NaN,nan,12.00,India,67.00,Mahipal Narwal,1.00,...,,43.75,64.00,,30.00,57.00,30.00,36.00,46.00,0.00
25,Aug 18 1986,Manjeet Chhillar,True,5 ft 9 in,0.00,5.00,India,69.00,Manjeet Chhillar,1.00,...,,54.58,621.00,,339.00,224.00,339.00,297.00,136.00,4.00
26,Sep 5 1993,Manoj Kumar,NaN,NaN,nan,4.00,India,70.00,Manoj Kumar,4.00,...,,25.66,187.00,,59.00,25.00,59.00,139.00,14.00,0.00
27,Jul 13 1993,Mohit Chhillar,True,5 ft 11 in,0.00,4.00,India,71.00,Mohit Chhillar,6.00,...,,50.18,552.00,,277.00,7.00,277.00,298.00,3.00,1.00
28,Jul 30 1983,Navneet Gautam,NaN,NaN,nan,9.00,India,72.00,Navneet Gautam,3.00,...,,24.09,83.00,,21.00,1.00,21.00,63.00,1.00,0.00
29,Oct 8 1980,Nilesh Shinde,NaN,NaN,nan,6.00,India,73.00,Nilesh Shinde,6.00,...,,42.16,287.00,,135.00,18.00,135.00,166.00,13.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,Feb 28 1993,More GB,False,6 ft,0.00,77.00,India,772.00,More GB,8.00,...,,59.64,57.00,,34.00,133.00,34.00,26.00,97.00,0.00
373,Nov 18 1991,Satpal,False,,nan,0.00,India,773.00,Satpal,6.00,...,,54.28,70.00,,38.00,5.00,38.00,38.00,5.00,0.00
374,NaN,NaN,NaN,NaN,nan,nan,NaN,nan,NaN,nan,...,,0.00,0.00,,0.00,1.00,0.00,0.00,3.00,0.00
375,Apr 17 1992,Muruthu M,NaN,NaN,nan,12.00,India,776.00,Muruthu M,7.00,...,,27.27,11.00,,3.00,0.00,3.00,8.00,1.00,0.00
376,Feb 16 1998,Pardeep Kandola,NaN,NaN,nan,22.00,India,777.00,Pardeep Kandola,6.00,...,,0.00,9.00,,0.00,0.00,0.00,9.00,0.00,0.00
377,Sep 10 1986,Narender,False,5 ft 8 in,0.00,3.00,India,778.00,Narender,1.00,...,,33.33,126.00,,42.00,0.00,42.00,89.00,0.00,0.00
378,None,Mugilan Batumalai,NaN,NaN,nan,13.00,Malaysia,780.00,Mugilan Batumalai,6.00,...,NaN,nan,nan,NaN,nan,nan,nan,nan,nan,nan
379,Oct 15 1993,Viraj Vishnu Landge,False,5 ft 7 in,0.00,90.00,India,784.00,Viraj Vishnu Landge,4.00,...,,25.89,112.00,,29.00,0.00,29.00,83.00,0.00,0.00
380,Nov 18 1994,Parvesh,False,,nan,9.00,India,786.00,Parvesh,8.00,...,,50.00,10.00,,5.00,7.00,5.00,6.00,11.00,0.00
381,Mar 18 1996,Sombir,NaN,NaN,nan,18.00,India,788.00,Sombir,8.00,...,NaN,nan,nan,NaN,nan,nan,nan,nan,nan,nan
382,Jan 15 1988,Satish,NaN,NaN,nan,5.00,India,790.00,Satish,6.00,...,,12.50,24.00,,3.00,0.00,3.00,21.00,0.00,0.00
383,None,Nitin Rawal,True,,0.00,14.00,India,791.00,Nitin Rawal,1.00,...,,47.87,94.00,,45.00,122.00,45.00,55.00,64.00,0.00
384,None,Tushar Balaram Bhoir,False,,nan,21.00,India,792.00,Tushar Bhoir,7.00,...,,15.78,19.00,,3.00,0.00,3.00,17.00,0.00,0.00
385,Dec 30 1998,Amit Kharb,False,,0.00,13.00,India,793.00,Amit Kharb,7.00,...,,18.18,11.00,,2.00,0.00,2.00,10.00,0.00,0.00
386,None,Amit Sheoran,False,,0.00,12.00,India,794.00,Amit Sheoran,9.00,...,,50.00,156.00,,78.00,0.00,78.00,83.00,1.00,0.00
387,Jan 1 1999,Monu,False,,0.00,55.00,India,795.00,Monu,8.00,...,,57.26,117.00,,67.00,75.00,67.00,60.00,66.00,0.00
388,None,Rinku Narwal,False,,0.00,66.00,India,796.00,Rinku Narwal,9.00,...,,48.10,185.00,,89.00,2.00,89.00,103.00,2.00,0.00
389,None,Vikash Khatri,False,,nan,11.00,India,797.00,Vikash Khatri,8.00,...,,0.00,1.00,,0.00,0.00,0.00,1.00,0.00,0.00
390,NaN,NaN,NaN,NaN,nan,nan,NaN,nan,NaN,nan,...,,25.00,8.00,,2.00,26.00,2.00,6.00,21.00,0.00
391,Jan 4 1989,Vittal Meti,False,,nan,21.00,India,2018.00,Vittal Meti,1.00,...,0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00
392,Jul 27 1996,Amit,False,5 ft 7 in,0.00,15.00,India,2020.00,Amit,4.00,...,,30.43,92.00,,28.00,2.00,28.00,67.00,0.00,0.00
393,Jan 24 1996,Anand V,False,,nan,44.00,India,2021.00,Anand V,8.00,...,,0.00,1.00,,0.00,3.00,0.00,1.00,5.00,0.00
394,Apr 1 1994,Ruturaj Shivaji Koravi,False,5 ft 9 in,0.00,12.00,India,2023.00,Ruturaj Koravi,9.00,...,,36.53,156.00,,57.00,0.00,57.00,102.00,0.00,0.00
395,Jul 7 1999,Arjun Deshwal,False,5 ft 8 in,0.00,2.00,India,2024.00,Arjun Deshwal,8.00,...,,40.00,5.00,,2.00,80.00,2.00,3.00,39.00,0.00
396,Sep 10 1994,Ajinkya Rohidas Kapre,False,5 ft 8 in,0.00,9.00,India,2025.00,Ajinkya Kapre,1.00,...,,0.00,1.00,,0.00,1.00,0.00,1.00,2.00,0.00
397,Dec 5 1991,Siddharth Sirish Desai,True,6 ft 2 in,0.00,9.00,India,2026.00,Siddharth Desai,8.00,...,,42.85,14.00,,6.00,355.00,6.00,8.00,141.00,0.00
398,Apr 3 1999,Abhishek Singh,False,5 ft 11 in,0.00,7.00,India,2028.00,Abhishek Singh,8.00,...,,22.58,31.00,,7.00,145.00,7.00,24.00,60.00,0.00
399,Jul 6 1997,Brijendra Singh Chaudhary,False,,nan,55.00,India,2034.00,Brijendra Chaudhary,1.00,...,0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00
400,Oct 25 1990,Anil,False,,nan,3.00,India,2040.00,Anil,8.00,...,0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00
401,Jul 26 1999,Gurdeep,False,5 ft 11 in,0.00,25.00,India,2041.00,Gurdeep,1.00,...,,66.66,3.00,,2.00,0.00,2.00,1.00,0.00,0.00

In [3]:
f = open('stats_squad.json')
data = json.load(f)
f.close()
data = map( lambda x: flatten_json( x, "__" ), data )
team_df = pd.DataFrame(list(data))

#Remove Columns with only One Value
#team_df = team_df.loc[:,team_df.apply(pd.Series.nunique) > 1]

# Drop unwanted columns
#columns_to_drop =['bio__facebook','bio__instagram','bio__official_website']
#team_df.drop(columns_to_drop, inplace=True, axis = 1)

# Only drop columns which have at least 50% non-NaNs
#team_df.dropna(thresh=int(team_df.shape[0] * .5), inplace=True, axis=1)

#team_df.rename(columns=lambda x: x.replace('over_all_stats__', 'team_'), inplace=True)
#team_df.rename(columns=lambda x: x.replace('bio__', 'team_'), inplace=True)

#column for column in df.columns column.contains('over_all_stats__')
#print(df['team_max_win_margin__match_id'])
#print(df['team_highest_score__match_id'])
#df
team_df

,language_lookup__country_id,language_lookup__country_name,language_lookup__date_of_birth,language_lookup__full_name,language_lookup__gender,language_lookup__is_captain,language_lookup__jersey_no,language_lookup__name,language_lookup__player_id,language_lookup__position_id,...,squads__squad__staff_details__member__country_id,squads__squad__staff_details__member__country_name,squads__squad__staff_details__member__full_name,squads__squad__staff_details__member__gender,squads__squad__staff_details__member__player_id,squads__squad__staff_details__member__role_id,squads__squad__staff_details__member__role_name,squads__team_details__short_name,squads__team_details__team_id,squads__team_details__team_name
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,None,Randhir Singh Sehrawat,m,128,6,Coach,Bengaluru,1,Bengaluru Bulls
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,India,Krishan Kumar Hooda,m,2466,6,Coach,Delhi,2,Dabang Delhi K.C.
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,India,Srinivas Reddy,m,2469,6,Coach,Jaipur,3,Jaipur Pink Panthers
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,None,BC Ramesh,m,812,6,Coach,Bengal,4,Bengal Warriors
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,India,Sanjeev Kumar,m,306,6,Coach,Mumbai,5,U Mumba
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,India,Ram Mehar Singh,m,808,6,Coach,Patna,6,Patna Pirates
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,India,Anup Kumar,m,29,6,Coach,Pune,7,Puneri Paltan
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,India,Gholamreza Mazandarani,m,2467,6,Coach,Hyderabad,8,Telugu Titans
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,India,Rakesh Kumar,m,88,6,Coach,Haryana,28,Haryana Steelers
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,India,E Bhaskaran,m,175,6,Coach,Tamil Nadu,29,Tamil Thalaivas
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,None,Darshan,m,2678,10,Analyst,UP,30,U.P. Yoddha
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,India,Manpreet Singh,m,309,6,Coach,Gujarat,31,Gujarat Fortunegiants
12,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,NaN,None,Randhir Singh,m,128,6,Coach,Bengaluru,1,Bengaluru Bulls
13,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,NaN,Player Id,Position Id,...,4.0,India,Arjun Singh,m,129,6,Coach,Patna,6,Patna Pirates
14,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,NaN,None,Randhir Singh,m,128,6,Coach,Bengaluru,1,Bengaluru Bulls
15,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Dr. Ramesh Bhendigiri,m,305,6,Coach,Delhi,2,Dabang Delhi K.C.
16,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,NaN,None,Balwan Singh,m,130,6,Coach,Jaipur,3,Jaipur Pink Panthers
17,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Jagdish Kumble,m,799,6,Coach,Bengal,4,Bengal Warriors
18,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Bhaskaran Edacherry,m,134,6,Coach,Mumbai,5,U Mumba
19,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Ram Mehar Singh,m,808,6,Coach,Patna,6,Patna Pirates
20,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,NaN,None,BC Ramesh,m,812,6,Coach,Pune,7,Puneri Paltan
21,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Naveen Kumar,m,810,6,Coach,Hyderabad,8,Telugu Titans
22,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Rambir Singh Khokhar,m,798,6,Coach,Haryana,28,Haryana Steelers
23,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,K Baskaran,m,175,6,Coach,Tamil Nadu,29,Tamil Thalaivas
24,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,J Udaya Kumar,m,133,6,Coach,UP,30,U.P. Yoddha
25,Country Id,Country Name,NaN,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Pankaj Shirsat,m,811,6,Coach,Gujarat,31,Gujarat Fortunegiants
26,Country Id,Country Name,Date Of Birth,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,NaN,None,Randhir Singh & BC Ramesh,m,128,6,Coach,Bengaluru,1,Bengaluru Bulls
27,Country Id,Country Name,Date Of Birth,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Krishan Kumar Hooda,m,2466,6,Coach,Delhi,2,Dabang Delhi K.C.
28,Country Id,Country Name,Date Of Birth,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Srinivas Reddy,m,2469,6,Coach,Jaipur,3,Jaipur Pink Panthers
29,Country Id,Country Name,Date Of Birth,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Jagdish Kumble,m,799,6,Coach,Bengal,4,Bengal Warriors
30,Country Id,Country Name,Date Of Birth,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Gholamreza Mahmoud Mazandarani,m,2467,6,Coach,Mumbai,5,U Mumba
31,Country Id,Country Name,Date Of Birth,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Ram Mehar Singh,m,808,6,Coach,Patna,6,Patna Pirates
32,Country Id,Country Name,Date Of Birth,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Ashan Kumar,m,2468,6,Coach,Pune,7,Puneri Paltan
33,Country Id,Country Name,Date Of Birth,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,K Jag Mohan,m,2465,6,Coach,Hyderabad,8,Telugu Titans
34,Country Id,Country Name,Date Of Birth,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Rambir Singh Khokhar,m,798,6,Coach,Haryana,28,Haryana Steelers
35,Country Id,Country Name,Date Of Birth,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,E Bhaskaran,m,175,6,Coach,Tamil Nadu,29,Tamil Thalaivas
36,Country Id,Country Name,Date Of Birth,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Jasveer Singh,m,2464,6,Coach,UP,30,U.P. Yoddha
37,Country Id,Country Name,Date Of Birth,Full Name,Gender,Is Captain,Jersey No,Name,Player Id,Position Id,...,4.0,India,Adani Wilmar Ltd,m,2461,4,Owner,Gujarat,31,Gujarat Fortunegiants